[package]
name = "tuner"
version = "0.5.4"
edition = "2021"

[lib]
name = "tuner_lib"
crate-type = ["rlib", "cdylib", "staticlib"]

[[bin]]
name = "tuner"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-http = "2.6.1"
