import{load,save,uid,addTracks,createPlaylist,deletePlaylist,removeFromPlaylist,loadPlaylistQueue,setCurrent,trackById}from './store.js';
import{mediaType,playTrack}from './player.js';
let state=load();const $=id=>document.getElementById(id);const player=$('player');
function persist(){save(state);render()}
function render(){document.querySelector('#app').dataset.ready='true';const lib=$('library-list');lib.innerHTML='';state.library.forEach(t=>{const li=document.createElement('li');li.className=state.currentId===t.id?'active':'';li.innerHTML='<span>'+t.name+'</span><span class=actions><button data-a=play data-id='+t.id+'>Play</button><button data-a=q data-id='+t.id+'>+Q</button></span>';lib.appendChild(li)});$('library-empty').style.display=state.library.length?'none':'block';const pl=$('playlist-list');pl.innerHTML='';state.playlists.forEach(p=>{const li=document.createElement('li');li.innerHTML='<span>'+p.name+' ('+p.trackIds.length+')</span><span class=actions><button data-a=loadpl data-id='+p.id+'>Load</button><button data-a=delpl data-id='+p.id+'>Del</button></span>';pl.appendChild(li);const sub=document.createElement('ul');p.trackIds.forEach((tid,i)=>{const tr=trackById(state,tid);if(!tr)return;const s=document.createElement('li');s.innerHTML='<span>'+(i+1)+'. '+tr.name+'</span><button data-a=play data-id='+tid+'>Play</button>';sub.appendChild(s)});pl.appendChild(sub)});$('playlist-empty').style.display=state.playlists.length?'none':'block';const q=$('queue-list');q.innerHTML='';state.queue.forEach((tid,i)=>{const tr=trackById(state,tid);if(!tr)return;const li=document.createElement('li');li.className=state.currentId===tid?'active':'';li.innerHTML='<span>'+(i+1)+'. '+tr.name+'</span><button data-a=play data-id='+tid+'>Play</button>';q.appendChild(li)});$('queue-empty').style.display=state.queue.length?'none':'block';const cur=trackById(state,state.currentId);$('now-playing').textContent=cur?'Playing: '+cur.name:'Select a track';}
async function importPaths(paths){state=addTracks(state,paths.map(p=>({id:uid(),name:p.split(/[\/]/).pop(),path:p,type:mediaType(p)})));persist()}
async function pickImport(){try{const{open}=await import('@tauri-apps/plugin-dialog');const sel=await open({multiple:true,filters:[{name:'Media',extensions:['mp4','mp3','wav','ogg','m4a','flac','aac','webm']}]});if(!sel)return;await importPaths(Array.isArray(sel)?sel:[sel])}catch{$('file-input').click()}}
function onFiles(ev){const files=[...ev.target.files||[]];state=addTracks(state,files.map(f=>({id:uid(),name:f.name,path:f.name,type:mediaType(f.name),blobUrl:URL.createObjectURL(f)})));persist();ev.target.value=''}
async function doPlay(id){state=setCurrent(state,id);await playTrack(player,trackById(state,id));persist()}
function stepQueue(n){if(!state.queue.length)return;const i=Math.max(0,state.queue.indexOf(state.currentId));doPlay(state.queue[(i+n+state.queue.length)%state.queue.length])}
document.body.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const{id}=b.dataset;const a=b.dataset.a;if(a==='play')return doPlay(id);if(a==='q'){state.queue=[...state.queue.filter(x=>x!==id),id];if(!state.currentId)state=setCurrent(state,id);persist()}if(a==='delpl'){state=deletePlaylist(state,id);persist()}if(a==='loadpl'){state=loadPlaylistQueue(state,id);persist();if(state.currentId)doPlay(state.currentId)}});
$('btn-import').onclick=pickImport;$('file-input').onchange=onFiles;$('btn-create-playlist').onclick=()=>{state=createPlaylist(state,$('playlist-name').value);$('playlist-name').value='';persist()};
$('btn-prev').onclick=()=>stepQueue(-1);$('btn-next').onclick=()=>stepQueue(1);render();
